### ISSUE TITLE
AstralKeys 3.67: attempt to call method 'GetUnit' (a nil value)

### ISSUE THREAD

**Issue by jeremy-hill** [astralguild/AstralKeys#69] opened 2022-12-14 11:12 UTC
5x AstralKeys/Lists/Friends.lua:658: attempt to call method 'GetUnit' (a nil value)
[string "@AstralKeys/Lists/Friends.lua"]:658: in function <AstralKeys/Lists/Friends.lua:655>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
....

**Comment by whatisboom** [comment] 2022-12-16 02:46
Still happening on v3.70

**Comment by Khazakdk** [comment] 2022-12-16 04:04
@whatisboom Is there a consistent trigger?  Are you mousing over the same thing when it happens?

**Comment by whatisboom** [comment] 2022-12-16 07:57
@Khazakdk it was pretty consistent when mousing over something in Azure Span... probably from HandyNotes. I'm not sure the exact object but can try and get some repro steps at some point, although i'm pretty busy this weekend.

**Comment by whatisboom** [comment] 2022-12-16 08:05
The Azure Pathfinder node in Azure Span repro's 100% of the time.

**Comment by pcrutcher** [comment] 2022-12-16 14:24
It definitely has something to do with handynotes when you mouse over an NPC icon.  Below is a more complete callstack showing that the handynotes handler called "handle_tooltip(tooltip, point, skip_label)" is calling comparison:SetHyperlink(("unit:Creature-0-0-0-0-%d"):format(point.npc)) on line 961.  That is resulting in the call to astral keys tooltip handler which is expecting a "self" parameter.  I don't know lua very well, especially in the context of wow, but it seems in this context the Astral tooltip handler is expecting "self" but getting something else as the first parameter...  so maybe a simple check to make sure self is the right type of object?

Stack: Interface/AddOns/AstralKeys/Lists/Friends.lua:658: attempt to call method 'GetUnit' (a nil value)
[string "@Interface/AddOns/AstralKeys/Lists/Friends.lua"]:658: in function <Interface/AddOns/AstralKeys/Lists/Friends.lua:655>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HandyNotes_DragonflightTreasures/handler/handler.lua"]:961: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:777>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HandyNotes_DragonflightTreasures/handler/handler.lua"]:1034: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:1010>
[string "=[C]"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:56: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:51>
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:166: in function `OnEnter'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:399: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:398>

**Comment by Khazakdk** [comment] 2022-12-16 14:32
Thanks for the further info.  AK shouldn't be interacting at all with tooltips from HandyNotes, I will look into this.

**Comment by Khazakdk** [comment] 2022-12-20 18:10
I have pushed what I hope is a fix for this, but I was unable to reproduce the problem myself to know if the fix will for sure work.  Please let me know if the issue persists.

**Comment by whatisboom** [comment] 2022-12-20 18:48
@Khazakdk seems to be fixed for me in the 3.71 update! Thanks!

**Closed** 2022-12-20 22:30 UTC
